services:
  - type: web
    name: iapt-backend
    env: python
    buildCommand: pip install -r backend/requirements-deploy.txt
    startCommand: python backend/init_db.py && gunicorn backend.wsgi:app --chdir backend --workers 3 --bind 0.0.0.0:${PORT}

  - type: static
    name: iapt-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
